volumes:
  csdl7_rabbitmq:
networks:
  csdl7:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    volumes:
      - csdl7_rabbitmq:/var/lib/rabbitmq
    networks:
      - csdl7
    ports:
      - "15672:15672"
      - "5672:5672"
